FROM golang:1.24-bookworm AS builder

ARG ANDROID_NDK_VERSION=r27c
ARG ANDROID_API=21
ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG ALL_PROXY
ARG NO_PROXY
ENV http_proxy=${HTTP_PROXY}
ENV https_proxy=${HTTPS_PROXY}
ENV all_proxy=${ALL_PROXY}
ENV no_proxy=${NO_PROXY}
WORKDIR /src

RUN apt-get update \
	&& apt-get install -y --no-install-recommends ca-certificates curl make unzip \
    && rm -rf /var/lib/apt/lists/* \
    && curl -fsSLo /tmp/android-ndk.zip "https://dl.google.com/android/repository/android-ndk-${ANDROID_NDK_VERSION}-linux.zip" \
    && unzip -q /tmp/android-ndk.zip -d /opt/android \
    && rm /tmp/android-ndk.zip

ENV ANDROID_NDK_HOME=/opt/android/android-ndk-r27c
COPY go.mod go.sum ./
COPY third_party/gadb ./third_party/gadb
RUN go mod download
COPY internal ./internal
COPY agent ./agent
RUN --mount=type=cache,target=/root/.cache/go-build,sharing=locked make -f /src/agent/Makefile-agent \
      ANDROID_NDK_HOME=${ANDROID_NDK_HOME} \
      ANDROID_API=${ANDROID_API} \
      build-agent

FROM scratch
COPY --from=builder /out /
